### ISSUE TITLE
Project Name does not show up on home page

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#15]
The project is not being properly stored and retrieved for submissions. 

<img width="1408" alt="Screen Shot 2022-03-17 at 12 20 59 PM" src="https://user-images.githubusercontent.com/1187616/158846570-21917208-4014-4b44-a100-fd7b46a1c224.png">

Find out what's changed between the merged version and the original master.  It looks like the project name on the Submission object is not being set.

**Comment by aaronlugo** [comment]
How Can I reproduce that?

**Comment by aaronlugo** [comment]
I did the assessment twice and did not showed up

**Comment by aaronlugo** [comment]
done

**Comment by teveritt** [comment]
Previously created projects will still show as unnamed but new ones will show up correctly.
